In [1]:
import joblib
import pandas as pd
import numpy as np
import src.utils as utils

In [2]:
a = joblib.load("log/0_categoric_raw.pkl")
a

stasiun
1527                DKI1 (Bunderan HI)
433   DKI5 (Kebon Jeruk) Jakarta Barat
1357  DKI5 (Kebon Jeruk) Jakarta Barat
1136              DKI2 (Kelapa Gading)
1097                DKI1 (Bunderan HI)
...                                ...
1802  DKI5 (Kebon Jeruk) Jakarta Barat
1433                  DKI3 (Jagakarsa)
977               DKI2 (Kelapa Gading)
983                   DKI3 (Jagakarsa)
747   DKI5 (Kebon Jeruk) Jakarta Barat

[1269 rows x 1 columns]

In [3]:
aa = joblib.load("log/y_0_categoric_raw.pkl")
aa

array([0, 1, 0, ..., 1, 1, 1])

In [5]:
a.shape, aa.shape

((1269, 1), (1269,))

In [6]:
b = joblib.load("log/1_categoric_encoded.pkl")
b

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
bb = joblib.load("log/y_1_categoric_encoded.pkl")
bb

array([0, 1, 0, ..., 1, 1, 1])

In [8]:
b.shape, bb.shape

((1269, 5), (1269,))

In [12]:
c = joblib.load("log/6_combined.pkl")
c = pd.DataFrame(c)
c

0    1    2    3    4         5         6         7         8   \
0     1.0  0.0  0.0  0.0  0.0 -1.862630 -1.529931 -1.252267 -0.738321   
1     0.0  0.0  0.0  0.0  1.0  0.294496  0.279296  0.000000  0.888292   
2     0.0  0.0  0.0  0.0  1.0 -1.930040 -1.817763 -1.170450 -0.941647   
3     0.0  1.0  0.0  0.0  0.0 -0.986297 -0.995387 -0.924997 -0.128341   
4     1.0  0.0  0.0  0.0  0.0  1.305649  1.183910 -1.743174  6.378109   
...   ...  ...  ...  ...  ...       ...       ...       ...       ...   
1264  0.0  0.0  0.0  0.0  1.0 -0.447016 -0.214129 -0.188637 -0.941647   
1265  0.0  0.0  1.0  0.0  0.0 -1.188528 -0.995387  0.547722 -0.941647   
1266  0.0  1.0  0.0  0.0  0.0  1.979751  1.348385  1.693170  0.074986   
1267  0.0  0.0  1.0  0.0  0.0  0.496727  0.197059  0.956811 -0.941647   
1268  0.0  0.0  0.0  0.0  1.0 -0.581836 -0.296367 -0.679543 -0.128341   

            9         10  
0    -0.952037  0.286426  
1    -0.882356  1.168644  
2    -0.673312 -1.147180  
3     2.532030 -1.367734  
4     0.859678  0.065871  
...        ...       ...  
1264 -0.394586 -0.154684  
1265 -0.185542 -1.147180  
1266  0.650634  0.837812  
1267 -0.603630 -0.154684  
1268 -1.300444  0.176148  

[1269 rows x 11 columns]

In [14]:
cc = joblib.load("log/y_6_combined.pkl")
cc = pd.DataFrame(cc, columns=[c.shape[1]])
cc

11
0      0
1      1
2      0
3      1
4      1
...   ..
1264   1
1265   1
1266   1
1267   1
1268   1

[1269 rows x 1 columns]

In [15]:
c.shape, cc.shape

((1269, 11), (1269, 1))

In [22]:
d = joblib.load("log/7_outliers_removed.pkl")
d

array([[ 1.        ,  0.        ,  0.        , ..., -0.73832059,
        -0.95203717,  0.28642556],
       [ 0.        ,  0.        ,  0.        , ...,  0.88829196,
        -0.88235583,  1.16864408],
       [ 0.        ,  0.        ,  0.        , ..., -0.94164716,
        -0.67331179, -1.14717954],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.07498569,
         0.65063378,  0.83781213],
       [ 0.        ,  0.        ,  1.        , ..., -0.94164716,
        -0.60363044, -0.1546837 ],
       [ 0.        ,  0.        ,  0.        , ..., -0.12834088,
        -1.3004439 ,  0.17614824]])

In [23]:
dd = joblib.load("log/y_7_outliers_removed.pkl")
dd

array([0, 1, 0, ..., 1, 1, 1])